name: mac_build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: |
        go build -v -tags pcap
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: phantomsocks
        path: /Users/runner/work/phantomsocks
