name: win_build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: |
        env GOOS=windows GOARCH=amd64 go build -tags windivert
        go build -v -tags windivert ./...
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: phantomsocks
        path: D:\a\phantomsocks\phantomsocks
